Check error condition after cvs returns.  Also remove -c option.
llvm-svn: 3728

diff --git a/llvm/cvsupdate b/llvm/cvsupdate
--- a/llvm/cvsupdate
+++ b/llvm/cvsupdate
@@ -1,4 +1,4 @@
-#!/bin/csh -f -c
+#!/bin/csh -f
 #
 # This script updates the entire tree, saves the output in cvs.out,
 # and then separately prints out the files that had merge conflicts,
@@ -31,6 +31,11 @@ end
 if ($doit == 1) then
     /bin/mv -f cvs.out cvs.out.bak
     cvs update -P -d >& cvs.out
+    if ($status != 0) then
+        echo "ERROR: CVS update failed: "
+	cat cvs.out
+	exit 1
+    endif
 else
     echo ""; echo "Not updating files."; echo ""
 endif
